### ISSUE TITLE
quintudiant

### ISSUE THREAD

**Issue by ghost** [MrWitzbold/zooming_out_scalar_field#1]
more details later

**Comment by ghost** [comment]
cos^2(x)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/46854844/136718795-ff0ff9e6-e535-402a-a449-f0c4d88f671d.png)

**Comment by ghost** [comment]
monday

**Comment by ghost** [comment]
it will merge

**Comment by MrWitzbold** [comment]
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF
ORAF

**Comment by MrWitzbold** [comment]
thy soul has been deprecated

**Comment by ghost** [comment]
reality is now closed

**Comment by MrWitzbold** [comment]
be wary that reality rewrite will be coming soon, don't get used to the relóid function

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/46854844/136868877-42a85fd6-21d4-4201-aca8-b70e682f3d66.png)
